context:
  version: "10.0.1"

package:
  name: selenium-standalone
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/selenium-standalone/-/selenium-standalone-${{ version }}.tgz
  sha256: 7d9683c966195e81e9f65c6839b1481830b8443357f6917943f00000e77db40a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs
    - openjdk

tests:
  - script:
      - "selenium-standalone 2>&1 | grep -q \"No action provided\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Installs a `selenium-standalone` command line to install and start a standalone selenium server
  homepage: https://github.com/webdriverio/selenium-standalone
  repository: https://github.com/webdriverio/selenium-standalone

extra:
  recipe-maintainers:
    - danielnachun
